# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="My user manuals 📚"
REPO_LICENSE=""
REPO_TOPICS="commodore,documentation,fairuse,terminal,usermanual"

# URLs section
REPO_GIT_SSH="git@github.com:chicks-net/my-user-manuals.git"
REPO_WEB_URL="https://github.com/chicks-net/my-user-manuals"

# Derived values
REPO_ORG_NAME="chicks-net"
REPO_REPO_NAME="my-user-manuals"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="false"
FLAG_CLAUDE_REVIEW="false"
FLAG_COPILOT_REVIEW="false"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
    "commodore"
    "documentation"
    "fairuse"
    "terminal"
    "usermanual"
)
