# .repo.toml

[about]
description = "My user manuals 📚"
topics = ["commodore", "documentation", "fairuse", "terminal", "usermanual"]

[urls]
git_ssh = "git@github.com:chicks-net/my-user-manuals.git"
web_url = "https://github.com/chicks-net/my-user-manuals"

[flags]
claude = false
claude-review = false
copilot-review = false
standard-release = true
