[Adtran_ISU_EXPRESS_128kbps_ISDN_Service_Unit_User_Manual]
original-filename = "Adtran_ISU_EXPRESS_128kbps_ISDN_Service_Unit_User_Manual_20251112011552_001.pdf"
manufacturer-model = "Adtran ISU Express"
scan-time = "2025-11-12T01:15:52-05:00"
tags = ["ISDN", "Adtran", "dial-up"]
